### ISSUE TITLE
[HU3] Gestor - Ingresos.

### ISSUE THREAD

**Issue by jesusmarzor** [jesusmarzor/Peluqueria#11]
Como **gestor**, quiero **predecir, usando los informes, cuántos son los ingresos** obtenidos en el negocio semanalmente dado que **tengo que saber cuanto puedo gastarme** para obtener ganancias y mejorar la empresa.

**Comment by JJ** [comment]
... Y no has hecho ningún issue que se refiera a ella, sólo el que hizo @Balrrach. En el objetivo 4 es esencial testear la lógica de negocio, y si no has desarrollado nada relacionado con ella, no puedes alcanzar el objetivo.
