### ISSUE TITLE
Pagar

### ISSUE THREAD

**Issue by jesusmarzor** [jesusmarzor/Peluqueria#13]
Como **cliente**, quiero **pagar el coste del servicio** en el momento de realizar la reserva ya que **si no pago en ese momento, no se me concederá la cita**.

**Comment by Balrrach** [comment]
Parece que el interesado en llevar la contabilidad de los pagos es el trabajador.

**Comment by jesusmarzor** [comment]
En esta **HU quiero reflejar que el cliente quiere pagar en el momento de hacer la reserva**, la contabilidad la hará la aplicación web conforme vayan pagando los clientes. Con esta aplicaciṕn, quiero evitar lo que comentas. Quiero que el trabajador se despreocupe de hacer cuentas.

He cambiado la HU porque no tenía mucho sentido que en esta historia hiciera mención a la contabilidad ya que al cliente no le incumbe para nada, este solo quiere que le hagan el servicio (en mi caso que le pele un peluquer@).

**Comment by JJ** [comment]
No tiene ningún beneficio para el cliente. Puede ser un issue (si interesa hacer algo en la lógica de negocio cuando pague), pero no una HU.
