### ISSUE TITLE
Estructuras Básicas 

### ISSUE THREAD

**Issue by Balrrach** [jesusmarzor/Peluqueria#14]
Es necesario crear las estructuras básicas para el futuro desarrollo de la lógica de negocio. A saber:
- Clase que gestione los productos que se emplean en la peluquería
- Clase que gestione los diferentes servicios que ofrece la peluquería
- Clase que gestione el stock de cada producto
- Clase que gestione el calendario
- Clase que gestione la aplicación

Está relaccionado con los issues #3, #4, #7, #8, #10 y #11

**Comment by Balrrach** [comment]
Esa discusión se llevó a cabo por teléfono aunque no haya quedado registrada.

**Comment by jesusmarzor** [comment]
Si, la estructura la tendrías que ir comentando en varios issues pero en el M0 solo puse una idea de lo que tenía en mente.

**Comment by jesusmarzor** [comment]
En la clase cita, he puesto nombre para que haya constancia de un dato del cliente, es verdad que para verificar 100% que es esa persona un DNI sería lo ideal ya que es único pero me parece que enseñar un DNI en una peluquería es innecesario.

Las peluquerías con las que hablé, cogen cita en una libreta y me dijeron que pedían solo el nombre ya que les parece suficiente para llamar al cliente y que pase a pelarse.

**Comment by jesusmarzor** [comment]
La **clase trabajador**, al ser una clase para autentificar a los trabajadores, podría tener un método como:
- autentificacionCorrecta(dni,contraseña) : true si this.dni == tdni && this.contraseña == contraseña

O algo por el estilo.

**Comment by jesusmarzor** [comment]
Lo de la idea de mi estructura en el M0 era por ayudar a mi compañero, pero ahora lo quito.

Había pensado en añadir una clase trabajador para que tenga sentido en un futuro lo del registro del trabajador. Pero se podría quitar ahora mismo de la estructura.
