### ISSUE TITLE
Identificadores

### ISSUE THREAD

**Issue by Balrrach** [jesusmarzor/Peluqueria#16]
La imposibilidad de usar variables de clase en Javascript obliga a proporcionar los identificadores manualmente a las clases que tengan identificador.

Relacionado con #14.

**Comment by jesusmarzor** [comment]
Podrías crear **variables static** antes del constructor con sus métodos static y llamar a esos métodos con **Clase.método**. Así todos los objetos de la clase tendrían la misma variable actualizada ya que se llama desde la propia clase.
