### ISSUE TITLE
Creacion de Productos Sin Cantidad Asociada

### ISSUE THREAD

**Issue by Balrrach** [jesusmarzor/Peluqueria#17]
Para dar una mayor flexibilidad al sistema se ha decidido permitir instanciar desde la clase 'controladora' productos sin necesidad de tener que introducir un stock.

Relacionado con #9.

**Comment by Balrrach** [comment]
Ligar al milestone 0

**Comment by jesusmarzor** [comment]
¿Para saber cuándo se acabará un producto no es necesario crear ese producto o stock con su cantidad?

Cuando se vaya usando el producto, se va gastando y cuando quede 'x' mililitos del producto (teniendo en cuenta en cuanto tiempo has gastado ese producto), el sistema te podría avisar que te faltan 'x' semanas para que se te acabe este producto.
