### ISSUE TITLE
Los objetos de la clase Cita no tienen información sobre la hora de la cita

### ISSUE THREAD

**Issue by jesusmarzor** [jesusmarzor/Peluqueria#29]
La clase Appointment no tiene la hora de la cita. ¿Cómo sabe el cliente la hora a la que tiene la cita? ¿Cómo sabe el trabajador a que hora tiene la cita cada cliente?

Avanza con la [HU1] #10

**Comment by JJ** [comment]
Ni tiene relación con ninguna HU (con lo que no se sabe *cómo* hay que cambiarlo), ni es un problema (con lo que no sabes qué problema hay y qué tienes que resolver)

**Comment by JJ** [comment]
"Cambiar class Appointment" también es una tarea, no un problema.

**Comment by jesusmarzor** [comment]
Ya he puesto lo que realmente es el problema.

**Comment by JJ** [comment]
Igual quieres cambiar el título también. "Cita sin hora" no parece que sea la formulación de un problema.
