### ISSUE TITLE
Anular cita.

### ISSUE THREAD

**Issue by jesusmarzor** [jesusmarzor/Peluqueria#4]
Como **cliente**, quiero **anular mis citas** concertadas dado que **no podría acudir por otros motivos**.

Avanza en la [HU1] #10

**Comment by Balrrach** [comment]
Que el cliente pueda anular cita supone implementar un sistema de login lo cual complica en exceso la implementación. Sugiero mover esto a un milestone posterior.

**Comment by jesusmarzor** [comment]
Los clientes no tienen cuenta de usuario. Los únicos que se tienen cuentas de usuario son los trabajadores para poder ver el calendario de citas.

Las reservas se guardan en la clase calendario mediante un boolean. 

Si el cliente que quiera anular su cita, tendría que aportar por ejemplo: su nombre, el dia, la hora y el servicio. 
Con estos datos se comprueba si todos son correctos(que ese dia, a esa hora, ese nombre tiene ese servicio), 
- si es correcto, se anularía la cita y se cambiaría el boolean de calendario.
- si no es correcto, no se anularía la cita.

**Comment by JJ** [comment]
Igual en este punto es un poco tarde, pero esto no es una historia de usuario, porque no representa ningún beneficio para el usuario, es simplemente una cosa que hay que hacer. Por favor, revisa todas las HUs para que sean, realmente, HUs. El resto conviértelas en simples issues.
